apiVersion: v1
kind: Service
metadata:
  name: delivery-listener-svc
  namespace: delivery
  labels:
    app: delivery-listener
spec:
  type: ClusterIP
  selector:
    app: delivery-listener
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
